class MainLocators:
    TITLE = ("css selector", "span[data-test='title']")
    CARDS = ("css selector", "div[data-test='inventory-item']")
    ADD_SAUCE_LABS_BACKPACK = ("css selector", "button[data-test='add-to-cart-sauce-labs-backpack']")
    REMOVE_SAUCE_LABS_BACKPACK = ("css selector", "button[data-test='remove-sauce-labs-backpack']")
    CARD_BTN = ("css selector", "a[data-test='shopping-cart-link']")
    BURGER_MENU = ("css selector", "div[class='bm-burger-button']")
    LOGOUT_BTN = ("css selector", "a[id='logout_sidebar_link']")
    SELECT = ("css selector", "select[data-test='product-sort-container']")
    PRICE_VALUE = ("css selector", "div[data-test='inventory-item-price']")
    NAME_VALUE = ("css selector", "div[data-test='inventory-item-name']")
    COUNT_ITEMS = ("css selector", "span[data-test='shopping-cart-badge']")
